# Generated by Django 5.2.12 on 2026-07-21 10:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import election.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='KuraVote', max_length=100)),
                ('institution_name', models.CharField(default='', max_length=200)),
                ('two_fa_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(default='green', max_length=20)),
                ('font_family', models.CharField(default='dmsans', max_length=20)),
                ('admin_font_size', models.CharField(default='md', max_length=5)),
                ('student_font_size', models.CharField(default='md', max_length=5)),
                ('primary_color', models.CharField(default='#16a34a', max_length=7)),
                ('sidebar_color', models.CharField(default='#14532d', max_length=7)),
                ('accent_color', models.CharField(default='#eab308', max_length=7)),
                ('custom_css', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admission_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_seen_tour', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admins',
                'indexes': [models.Index(fields=['username'], name='admins_usernam_fc3a6f_idx'), models.Index(fields=['email'], name='admins_email_fe9722_idx')],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(blank=True, help_text='Optional message shown to students on their dashboard', null=True)),
                ('election_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('rerun', 'Re-run (Tie Resolution)')], default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'elections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='elections_status_eb3191_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_notification', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('max_votes', models.PositiveIntegerField(default=1)),
                ('is_rerun', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='election.election')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['position_name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(0)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to=election.models.candidate_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.position')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
                'ordering': ['position', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='RerunElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('rerun', 'Re-run (Tie Resolution)')], default='inactive', max_length=10)),
                ('tied_candidates_data', models.JSONField(help_text='Data of tied candidates from original election')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reruns', to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reruns', to='election.position')),
            ],
            options={
                'verbose_name': 'Rerun Election',
                'verbose_name_plural': 'Rerun Elections',
                'db_table': 'rerun_elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RerunVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerun_votes', to='election.candidate')),
                ('rerun_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.rerunelection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerun_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rerun Vote',
                'verbose_name_plural': 'Rerun Votes',
                'db_table': 'rerun_votes',
            },
        ),
        migrations.CreateModel(
            name='TiebreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tied_candidates', models.JSONField()),
                ('winner_candidate_id', models.IntegerField()),
                ('winner_name', models.CharField(max_length=200)),
                ('method', models.CharField(default='earliest_vote', max_length=50)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak_logs', to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak_logs', to='election.position')),
            ],
            options={
                'db_table': 'tiebreak_logs',
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_admissi_664d58_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_email_b942ac_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name'], name='students_first_n_73f9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name'], name='students_last_na_b4c560_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', 'is_read'], name='notificatio_student_67112a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_admin_notification', 'is_read'], name='notificatio_is_admi_58b16b_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['election'], name='positions_electio_0c6656_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election', 'position_name')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['position'], name='candidates_positio_f788c0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['student'], name='candidates_student_8381ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('student', 'position')},
        ),
        migrations.AddIndex(
            model_name='rerunvote',
            index=models.Index(fields=['rerun_election', 'student'], name='rerun_votes_rerun_e_65d2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='rerunvote',
            index=models.Index(fields=['rerun_election', 'candidate'], name='rerun_votes_rerun_e_1afbe6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rerunvote',
            unique_together={('student', 'rerun_election')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'position', 'candidate'], name='votes_electio_41d593_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['student', 'election'], name='votes_student_13061a_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election'], name='votes_electio_7d3e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('student', 'position', 'election')},
        ),
    ]
