# Generated by Django 5.2.12 on 2026-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_name_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='announcement',
            field=models.TextField(blank=True, help_text='Optional message shown to students on their dashboard', null=True),
        ),
    ]
