# Generated by Django 5.2.12 on 2026-05-11 14:19

import django.core.validators
import election.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=election.models.candidate_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
