# Generated by Django 5.2.12 on 2026-06-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_alter_candidate_manifesto_alter_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_admin_notification', 'is_read'], name='notificatio_is_admi_58b16b_idx'),
        ),
    ]
