# Generated by Django 5.2.12 on 2026-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_notification_is_admin_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
