# Generated by Django 5.2.12 on 2026-07-16 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_student_has_seen_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='KuraVote', max_length=100)),
                ('institution_name', models.CharField(default='', max_length=200)),
                ('two_fa_enabled', models.BooleanField(default=True)),
                ('admin_font_size', models.CharField(default='md', max_length=5)),
                ('student_font_size', models.CharField(default='md', max_length=5)),
                ('background_style', models.CharField(default='default', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='TiebreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tied_candidates', models.JSONField()),
                ('winner_candidate_id', models.IntegerField()),
                ('winner_name', models.CharField(max_length=200)),
                ('method', models.CharField(default='earliest_vote', max_length=50)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak_logs', to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreak_logs', to='election.position')),
            ],
            options={
                'db_table': 'tiebreak_logs',
                'ordering': ['-resolved_at'],
            },
        ),
    ]
