# Generated by Django 5.2.12 on 2026-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('election', '0008_systemsettings_tiebreaklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='background_style',
        ),
        migrations.AddField(
            model_name='position',
            name='is_rerun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='accent_color',
            field=models.CharField(default='#eab308', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='font_family',
            field=models.CharField(default='dmsans', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#16a34a', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_color',
            field=models.CharField(default='#14532d', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('rerun', 'Re-run (Tie Resolution)')], default='inactive', max_length=10),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name'], name='students_first_n_73f9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name'], name='students_last_na_b4c560_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx'),
        ),
    ]
