# Generated by Django 5.2.12 on 2026-07-19 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_remove_systemsettings_background_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TieResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tied_vote_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Admin Decision'), ('rerun', 'Rerun Election Scheduled'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tie_resolutions', to='election.election')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tie_resolution', to='election.position')),
                ('rerun_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rerun_for', to='election.election')),
                ('tied_candidates', models.ManyToManyField(blank=True, related_name='tie_resolutions', to='election.candidate')),
            ],
            options={
                'db_table': 'tie_resolutions',
                'ordering': ['-detected_at'],
            },
        ),
    ]
