# Generated by Django 5.2.12 on 2026-07-21 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_pushsubscription_delete_tieresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerunElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('rerun', 'Re-run (Tie Resolution)')], default='inactive', max_length=10)),
                ('tied_candidates_data', models.JSONField(help_text='Data of tied candidates from original election')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reruns', to='election.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reruns', to='election.position')),
            ],
            options={
                'verbose_name': 'Rerun Election',
                'verbose_name_plural': 'Rerun Elections',
                'db_table': 'rerun_elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RerunVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerun_votes', to='election.candidate')),
                ('rerun_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.rerunelection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerun_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rerun Vote',
                'verbose_name_plural': 'Rerun Votes',
                'db_table': 'rerun_votes',
                'indexes': [models.Index(fields=['rerun_election', 'student'], name='rerun_votes_rerun_e_65d2e8_idx'), models.Index(fields=['rerun_election', 'candidate'], name='rerun_votes_rerun_e_1afbe6_idx')],
                'unique_together': {('student', 'rerun_election')},
            },
        ),
    ]
