"""
Django settings for kuravote project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'crispy_forms',
    'crispy_bootstrap5',

    # Our app
    'election',
]

MIDDLEWARE = [
    # compresses responses for faster load times
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # CORRECT — points to election/middleware.py
    'election.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'kuravote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'election.utils.active_election',  # custom context processor for active election
            ],
        },
    },
]

WSGI_APPLICATION = 'kuravote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     os.getenv('DB_NAME'),
        'USER':     os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST':     os.getenv('DB_HOST', 'localhost'),
        'PORT':     os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',        # supports all unicode + emojis
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # strict mode
        },
    }
}

# ─── Custom Auth ─────────────────────────────────────────
# Tells Django to use our custom Student model for auth
AUTH_USER_MODEL = 'election.Student'


AUTHENTICATION_BACKENDS = [
    'election.backends.AdmissionNumberBackend',  # student login
    'django.contrib.auth.backends.ModelBackend',  # admin login
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# ─── Session Security ────────────────────────────────────
SESSION_COOKIE_AGE = 3600        # 1 hour timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True    # ends when browser closes
SESSION_COOKIE_HTTPONLY = True        # JS cannot access cookie
SESSION_COOKIE_SECURE = False       # set True when HTTPS is live
SESSION_SAVE_EVERY_REQUEST = True        # resets timeout on activity


# ─── Security Headers ────────────────────────────────────
CSRF_COOKIE_HTTPONLY = False       # needed for JS form submits
X_FRAME_OPTIONS = 'DENY'      # prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True


# ─── Login / Logout Redirects ────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Eager loading — serve compressed static files
STATICFILES_STORAGE = (
    'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
)
STATIC_ROOT = BASE_DIR / 'staticfiles'  # for production collectstatic

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─── Cache (for live results speed) ─────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'kuravote-cache',
    }
}


# ─── File Upload Limits ──────────────────────────────────
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880    # 5MB max upload size
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880    # 5MB max file size
