from django.urls import path
from . import views

urlpatterns = [

    # ── Authentication ────────────────────────────────────
    path(
        '',
        views.login_view,
        name='login'
    ),
    path(
        'login/',
        views.login_view,
        name='login'
    ),
    path(
        'logout/',
        views.logout_view,
        name='logout'
    ),
    path(
        'change-password/',
        views.change_password_view,
        name='change_password'
    ),

    # ── Student Side ──────────────────────────────────────
    path(
        'dashboard/',
        views.student_dashboard,
        name='student_dashboard'
    ),
    path(
        'ballot/',
        views.ballot_view,
        name='ballot'
    ),
    path(
        'vote/',
        views.cast_vote,
        name='cast_vote'
    ),
    path(
        'results/',
        views.student_results,
        name='student_results'
    ),
    path(
        'profile/',
        views.student_profile,
        name='student_profile'
    ),

    # ── Admin Side ────────────────────────────────────────
    path(
        'admin-panel/',
        views.admin_dashboard,
        name='admin_dashboard'
    ),
    path(
        'admin-panel/elections/',
        views.admin_elections,
        name='admin_elections'
    ),
    path(
        'admin-panel/elections/create/',
        views.admin_election_create,
        name='admin_election_create'
    ),
    path(
        'admin-panel/elections/<int:pk>/edit/',
        views.admin_election_edit,
        name='admin_election_edit'
    ),
    path(
        'admin-panel/elections/<int:pk>/delete/',
        views.admin_election_delete,
        name='admin_election_delete'
    ),
    path(
        'admin-panel/elections/<int:pk>/activate/',
        views.admin_election_activate,
        name='admin_election_activate'
    ),
    path(
        'admin-panel/elections/<int:pk>/close/',
        views.admin_election_close,
        name='admin_election_close'
    ),
    path(
        'admin-panel/positions/',
        views.admin_positions,
        name='admin_positions'
    ),
    path(
        'admin-panel/positions/create/',
        views.admin_position_create,
        name='admin_position_create'
    ),
    path(
        'admin-panel/positions/<int:pk>/edit/',
        views.admin_position_edit,
        name='admin_position_edit'
    ),
    path(
        'admin-panel/positions/<int:pk>/delete/',
        views.admin_position_delete,
        name='admin_position_delete'
    ),
    path(
        'admin-panel/candidates/',
        views.admin_candidates,
        name='admin_candidates'
    ),
    path(
        'admin-panel/candidates/create/',
        views.admin_candidate_create,
        name='admin_candidate_create'
    ),
    path(
        'admin-panel/candidates/<int:pk>/edit/',
        views.admin_candidate_edit,
        name='admin_candidate_edit'
    ),
    path(
        'admin-panel/candidates/<int:pk>/delete/',
        views.admin_candidate_delete,
        name='admin_candidate_delete'
    ),
    path(
        'admin-panel/students/',
        views.admin_students,
        name='admin_students'
    ),
    path(
        'admin-panel/students/upload-csv/',
        views.admin_upload_csv,
        name='admin_upload_csv'
    ),
    path(
        'admin-panel/students/<int:pk>/reset-password/',
        views.admin_reset_password,
        name='admin_reset_password'
    ),
    path(
        'admin-panel/students/<int:pk>/toggle-active/',
        views.admin_toggle_student,
        name='admin_toggle_student'
    ),
    path(
        'admin-panel/results/<int:election_id>/',
        views.admin_live_results,
        name='admin_live_results'
    ),
    path(
        'admin-panel/results/<int:election_id>/api/',
        views.admin_results_api,
        name='admin_results_api'
    ),
    path(
        'admin-panel/reports/<int:election_id>/',
        views.admin_reports,
        name='admin_reports'
    ),
    path(
        'admin-panel/reports/<int:election_id>/export/pdf/',
        views.export_pdf,
        name='export_pdf'
    ),
    path(
        'admin-panel/reports/<int:election_id>/export/excel/',
        views.export_excel,
        name='export_excel'
    ),
    path(
        'admin-panel/audit-log/',
        views.admin_audit_log,
        name='admin_audit_log'
    ),
    path(
        'admin-panel/settings/',
        views.admin_settings,
        name='admin_settings'
    ),
]
